config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :vehicles
  devise_for :users

   root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:date, :reason, :km_nbr, :tax_coef, :journey, :departure, :arrival)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:brand, :model, :horsepower)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppliKm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :km_nbr %><br>
    <%= f.number_field :km_nbr %>
  </div>
  <div class="field">
    <%= f.label :tax_coef %><br>
    <%= f.number_field :tax_coef %>
  </div>
  <div class="field">
    <%= f.label :journey %><br>
    <%= f.number_field :journey %>
  </div>
  <div class="field">
    <%= f.label :departure %><br>
    <%= f.text_area :departure %>
  </div>
  <div class="field">
    <%= f.label :arrival %><br>
    <%= f.text_area :arrival %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lists</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Reason</th>
      <th>Km nbr</th>
      <th>Tax coef</th>
      <th>Journey</th>
      <th>Departure</th>
      <th>Arrival</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.date %></td>
        <td><%= list.reason %></td>
        <td><%= list.km_nbr %></td>
        <td><%= list.tax_coef %></td>
        <td><%= list.journey %></td>
        <td><%= list.departure %></td>
        <td><%= list.arrival %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @list.date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @list.reason %>
</p>

<p>
  <strong>Km nbr:</strong>
  <%= @list.km_nbr %>
</p>

<p>
  <strong>Tax coef:</strong>
  <%= @list.tax_coef %>
</p>

<p>
  <strong>Journey:</strong>
  <%= @list.journey %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @list.departure %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @list.arrival %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :horsepower %><br>
    <%= f.number_field :horsepower %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Horsepower</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.brand %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.horsepower %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @vehicle.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Horsepower:</strong>
  <%= @vehicle.horsepower %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>